# Generated by Django 3.0.6 on 2020-06-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_hash', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('os', models.CharField(default='Other', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(default='Other', max_length=200)),
                ('browser', models.CharField(default='Other', max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.URL')),
            ],
        ),
    ]
